### PR TITLE
Fix a tiny typo in the Readme

### PR DESCRIPTION
**Pull request by awatson1978**
Hi Gadi!
Thanks for piecing together this event-hooks package!  :)
There's a tiny typo in the docs, fyi.

### CODE REVIEW

**Comment by BenjaminRH** [comment]
Thanks for noticing that! Incidentally, I'm not Gadi, I'm Benjamin. But I'm glad you like it :)

**Comment by awatson1978** [comment]
Ooops!  Sorry about the name mix-up.  I had like 50 browser windows open, and was working on both your 'meteor-event-hooks' package and Gadi's 'headers' package at the same time.  Sorry about that.  

By the way, your event-hooks package rocks, and is maybe saving the project we're working on.  This is _exactly_ what we were looking for.

**Comment by BenjaminRH** [comment]
No problem :). That's great, I always love to hear that. Incidentally, I'm thinking of a change to the way the package works, and could go two possible ways. I'm trying to get feedback on which one people would prefer.
- Option A: I make the package use a lot less memory and become more efficient, but can no longer pass the `userId` to the `onDeleteUser` hook
- Option B: I can also pass the deleted user document to the `onDeleteUser` hook, but things become a little bit more inefficient than they are currently.

**Comment by awatson1978** [comment]
Huh.  Honestly, we're not using it in a way that either of those would make a whole lot of difference to us, I think.  At least, not yet.  We're using event-hooks to manage a 3rd party video streaming API, which is sensitive to the reactive templates.  So, on a `onDeleteUser` hook, it would be convenient to have the `userId`, so we can pop a video stream off the stack.  But that would be about the extent of our use of an `onDeleteUser` hook.  It would be a fairly rare occurrence for us, I would think.

What we **did** find, was that we immediately wanted to complement event-hooks with `window.onload` and `window.onbeforeunload` hooks.

After an evening of research, I came up with the following syntax which works for loading and unloading pages (it was the 'onbeforeunload' syntax that was tough.).  We'd be really excited to see `Hooks.onPageLoad()` and `Hooks.onBeforePageUnload()` syntax introduced.  Not sure if you want to introduce syntax that requires jQuery, but here's the code we're using:

``` js
// Hooks.onPageLoad()  function, perhaps?
window.onload = function(){
  console.log('window.onload');
};

// Hooks.onPageBeforeUnload(), perhaps?
var activateAlertBeforeLeaving = false;
var alertMessage = "Are you sure you want to leave"?
Meteor.startup(function(){
    // I could only get the jQuery version to work.  Tried the addEventListener version, but no luck.
    $(window).bind('beforeunload', function() {
        onBeforeUnload();
        if(activateAlertBeforeLeaving){
            // return a string, and Chrome pops up an alert box
            // might need to check behavior on multiple browsers?
            return alertMessage;
        }else{
            // return null creates a silent hook
            return null;
        }
    });
});
// helper function.  Might be an ideal way to plug in Hooks.onBeforePageUnload()
onBeforeUnload = function(){
    console.log('onbeforeunload');

    // had to log an event to the server to confirm the `onbeforeunload` event was firing
    // because the browser window closes before you can inspect the console.log
    // the logEventOnServer function simply logged the message to the server log, btw
    //
    // Meteor.call('logEventOnServer', 'onbeforeunload', function (error, result){
    //    console.log('onbeforeunload');
    // });
}

```

**Pull request merged**
